src/StoreYxWms/Controllers/StockInController.cs
using IServices;
using Microsoft.AspNetCore.Mvc;
using SqlSugar;
using System.Linq;
using YL.Core.Dto;
using YL.Core.Entity;
using YL.Core.Entity.Fluent.Validation;
using YL.NetCore.Attributes;
using YL.NetCore.NetCoreApp;
using YL.Utils.Extensions;
using YL.Utils.Pub;

namespace StoreYxWms.Controllers
{
    public class StockInController : BaseController
    {
        private readonly IWms_stockinServices _stockinServices;
        private readonly IWms_supplierServices _supplierServices;
        private readonly ISys_dictServices _dictServices;
        private readonly ISys_serialnumServices _serialnumServices;
        private readonly IWms_stockindetailServices _stockindetailServices;
        private readonly SqlSugarClient _client;

        public StockInController(
            IWms_stockindetailServices stockindetailServices,
            ISys_serialnumServices serialnumServices,
            ISys_dictServices dictServices,
            IWms_supplierServices supplierServices,
            IWms_stockinServices stockinServices,
            SqlSugarClient client
            )
        {
            _stockindetailServices = stockindetailServices;
            _serialnumServices = serialnumServices;
            _dictServices = dictServices;
            _supplierServices = supplierServices;
            _stockinServices = stockinServices;
            _client = client;
        }

        [HttpGet]
        [CheckMenu]
        public IActionResult Index()
        {
            var list = _dictServices.Queryable().Where(c => c.IsDel == 1 && c.DictType == PubDictType.stockin.ToInt32().ToString()).ToList();
            var stockInStatus = EnumExt.ToKVListLinq<StockInStatus>();
            ViewBag.StockInType = list;
            ViewBag.StockInStatus = stockInStatus;
            return View();
        }

        /// <summary>
        /// 主表
        /// </summary>
        /// <param name="bootstrap">参数</param>
        /// <returns></returns>
        [HttpPost]
        [OperationLog(LogType.select)]
        public ContentResult List([FromForm] PubParams.StockInBootstrapParams bootstrap)
        {
            var sd = _stockinServices.PageList(bootstrap);
            return Content(sd);
        }

        /// <summary>
        /// 明细
        /// </summary>
        /// <param name="id">主表id</param>
        /// <returns></returns>
        [HttpPost]
        [OperationLog(LogType.select)]
        public ContentResult ListDetail(string pid)
        {
            var sd = _stockindetailServices.PageList(pid);
            return Content(sd);
        }

        [HttpGet]
        public IActionResult Add(string id)
        {
            var model = new Wms_stockin();
            if (id.IsEmpty())
            {
                return View(model);
            }
            else
            {
                model = _stockinServices.QueryableToEntity(c => c.StockInId == SqlFunc.ToInt64(id) && c.IsDel == 1);
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult Detail(string id, string pid)
        {
            var model = new Wms_stockindetail();
            if (id.IsEmptyZero())
            {
                model.StockInId = pid.ToInt64();
                return View(model);
            }
            else
            {
                model = _stockindetailServices.QueryableToEntity(c => c.StockInDetailId == SqlFunc.ToInt64(id) && c.IsDel == 1);
                return View(model);
            }
        }

        [HttpPost]
        [FilterXss]
        [OperationLog(LogType.addOrUpdate)]
        public IActionResult AddOrUpdate([FromForm] Wms_stockin model, [FromForm] string id)
        {
            var validator = new StockInFluent();
            var results = validator.Validate(model);
            var success = results.IsValid;
            if (!success)
            {
                string msg = results.Errors.Aggregate("", (current, item) => (current + item.ErrorMessage + "</br>"));
                return BootJsonH((PubEnum.Failed.ToInt32(), msg));
            }
            if (id.IsEmptyZero())
            {
                if (!model.OrderNo.IsEmpty())
                {
                    if (_stockinServices.IsAny(c => c.OrderNo == model.OrderNo))
                    {
                        return BootJsonH((false, PubConst.StockIn1));
                    }
                }
                model.StockInNo = _serialnumServices.GetSerialnum(UserDtoCache.UserId, "Wms_stockin");
                model.StockInId = PubId.SnowflakeId;
                model.StockInStatus = StockInStatus.initial.ToByte();
                model.CreateBy = UserDtoCache.UserId;
                bool flag = _stockinServices.Insert(model);
                return BootJsonH(flag ? (flag, PubConst.Add1) : (flag, PubConst.Add2));
            }
            else
            {
                model.StockInId = id.ToInt64();
                model.ModifiedBy = UserDtoCache.UserId;
                model.ModifiedDate = DateTimeExt.DateTime;
                var flag = _stockinServices.Update(model);
                return BootJsonH(flag ? (flag, PubConst.Update1) : (flag, PubConst.Update2));
            }
        }

        [HttpPost]
        [FilterXss]
        [OperationLog(LogType.addOrUpdate)]
        public IActionResult AddOrUpdateD([FromForm] Wms_stockindetail model, [FromForm] string id)
        {
            var validator = new StockInDetailFluent();
            var results = validator.Validate(model);
            var success = results.IsValid;
            if (!success)
            {
                string msg = results.Errors.Aggregate("", (current, item) => (current + item.ErrorMessage + "</br>"));
                return BootJsonH((PubEnum.Failed.ToInt32(), msg));
            }
            if (id.IsEmptyZero())
            {
                model.StockInDetailId = PubId.SnowflakeId;
                model.Status = StockInStatus.initial.ToByte();
                model.CreateBy = UserDtoCache.UserId;
                bool flag = _stockindetailServices.Insert(model);
                return BootJsonH(flag ? (flag, PubConst.Add1) : (flag, PubConst.Add2));
            }
            else
            {
                model.StockInDetailId = id.ToInt64();
                model.ModifiedBy = UserDtoCache.UserId;
                model.ModifiedDate = DateTimeExt.DateTime;
                var flag = _stockindetailServices.Update(model);
                return BootJsonH(flag ? (flag, PubConst.Update1) : (flag, PubConst.Update2));
            }
        }

        /// <summary>
        /// 审核
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [OperationLog(LogType.update)]
        public IActionResult Auditin(string id)
        {
            var list = _stockindetailServices.QueryableToList(c => c.IsDel == 1 && c.StockInId == SqlFunc.ToInt64(id));
            if (!list.Any())
            {
                return BootJsonH((false, PubConst.StockIn4));
            }
            var flag = _stockinServices.Auditin(UserDtoCache.UserId, SqlFunc.ToInt64(id));
            return BootJsonH(flag ? (flag, PubConst.StockIn2) : (flag, PubConst.StockIn3));
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id">主表id</param>
        /// <returns></returns>
        [HttpGet]
        [OperationLog(LogType.delete)]
        public IActionResult Delete(string id)
        {
            var flag = _client.Ado.UseTran(() =>
            {
                _client.Updateable(new Wms_stockindetail { IsDel = 0, ModifiedBy = UserDtoCache.UserId, ModifiedDate = DateTimeExt.DateTime })
                .UpdateColumns(c => new { c.IsDel, c.ModifiedBy, c.ModifiedDate })
                .Where(c => c.StockInId == SqlFunc.ToInt64(id) && c.IsDel == 1).ExecuteCommand();
                _client.Updateable(new Wms_stockin { StockInId = SqlFunc.ToInt64(id), IsDel = 0, ModifiedBy = UserDtoCache.UserId, ModifiedDate = DateTimeExt.DateTime })
               .UpdateColumns(c => new { c.IsDel, c.ModifiedBy, c.ModifiedDate })
               .ExecuteCommand();
            }).IsSuccess;
            return BootJsonH(flag ? (flag, PubConst.Delete1) : (flag, PubConst.Delete2));
        }

        /// <summary>
        /// 删除明细
        /// </summary>
        /// <param name="id">明细id</param>
        /// <returns></returns>
        [HttpGet]
        [OperationLog(LogType.delete)]
        public IActionResult DeleteDetail(string id)
        {
            var flag = _stockindetailServices.Update(
                 new Wms_stockindetail { IsDel = 0, ModifiedBy = UserDtoCache.UserId, ModifiedDate = DateTimeExt.DateTime },
                 c => new { c.IsDel, c.ModifiedBy, c.ModifiedDate },
                 c => c.StockInDetailId == SqlFunc.ToInt64(id)
                 );
            return BootJsonH(flag ? (flag, PubConst.Delete1) : (flag, PubConst.Delete2));
        }

        [HttpGet]
        public IActionResult PreviewJson(string id)
        {
            var str = _stockinServices.PrintList(id);
            return Content(str);
        }
    }
}

src/StoreYxWms/ViewComponents/DictViewComponent.cs
using IServices;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using YL.Utils.Extensions;
using YL.Utils.Pub;

namespace StoreYxWms.ViewComponents
{
    public class DictViewComponent : ViewComponent
    {
        private readonly ISys_dictServices _dictServices;

        public DictViewComponent(ISys_dictServices dictServices)
        {
            _dictServices = dictServices;
        }

        public async Task<IViewComponentResult> InvokeAsync(string type)
        {
            var d = EnumExt.GetDescription<PubDictType>(type);
            var value = 0;
            var obj = type.ToEnum<PubDictType>();
            switch (obj)
            {
                case PubDictType.unit:
                    value = Convert.ToInt32(PubDictType.unit);
                    ViewData["field"] = "Unit";
                    break;

                case PubDictType.material:
                    value = Convert.ToInt32(PubDictType.material);
                    ViewData["field"] = "MaterialType";
                    break;

                case PubDictType.stockin:
                    value = Convert.ToInt32(PubDictType.stockin);
                    ViewData["field"] = "StockinType";
                    break;

                case PubDictType.stockout:
                    value = Convert.ToInt32(PubDictType.stockout);
                    ViewData["field"] = "StockoutType";
                    break;

                case PubDictType.device:
                    value = Convert.ToInt32(PubDictType.device);
                    ViewData["field"] = "DeviceType";
                    break;

                case PubDictType.property:
                    value = Convert.ToInt32(PubDictType.property);
                    ViewData["field"] = "PropertyType";
                    break;

                default:
                    break;
            }
            var list = await _dictServices.Queryable().Where(c => c.IsDel == 1 && c.DictType == SqlSugar.SqlFunc.ToString(value))
               .ToListAsync();
            ViewData["type"] = d;
            return View(list);
        }
    }
}

src/StoreYxWms/Views/StockIn/Add.cshtml
@{
    Layout = "_LayoutH";
    @model Wms_stockin
}
@section styles{
    <link rel="stylesheet" href="~/css/bootstrap-select.min.css" />
}
<div id="app" v-cloak>
    <form class="form-horizontal" onsubmit="return false">
        <div class="box-body">
            <div class="form-group">
                <label class="col-sm-2 control-label">入库单编号</label>
                <div class="col-sm-10">
                    <input class="form-control" placeholder="系统自动生成" disabled v-model="StockInNo" type="text">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">订单号</label>
                <div class="col-sm-10">
                    <input class="form-control" v-model="OrderNo" v-focus type="text">
                </div>
            </div>
            @await Component.InvokeAsync("Dict", YL.Utils.Pub.PubDictType.stockin.ToString())
            <div class="form-group">
                <label class="form-label col-sm-2">供应商 </label>
                <div class="col-sm-10">
                    <select size="1" v-model="SupplierId" class="show-menu-arrow show-tick selectpicker form-control" data-live-search="true"></select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">备注</label>
                <div class="col-sm-10">
                    <textarea v-model="Remark" class="form-control" rows="3" placeholder="备注...100个字符以内"></textarea>
                    <p class="textarea-numberbar"><em class="textarea-length">{{count}}</em>/100</p>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="pull-right box-tools">
                <input v-on:click="addL" class="btn btn-primary radius" type="submit" v-model="submit">
            </div>
        </div>
    </form>
</div>

@section scripts{
    <script src="~/js/bootstrap-select.min.js"></script>
    <script src="~/js/defaults-zh_CN.min.js"></script>
    <script>
        $(function () {
            $('.selectpicker').on('show.bs.select', function (e, clickedIndex, isSelected, previousValue) {
                var divdom = $("div[class='bs-searchbox']")[0].childNodes[0];
                $(divdom).on("input propertychange", function () {
                    var dom = $("li[class='no-results']");
                    var text = divdom.value;
                    if (dom.length > 0) {
                        app.searchSupplier(text, 2);
                    }
                    if (app.SupplierList.length <= 0) {
                        app.searchSupplier(text, 2);
                    }
                    //if (dom.length > 0) {
                    //        yui.$axiosget('/StockIn/Search?text=' + text).then(function (res) {
                    //            var data = res.data.rows;
                    //            var html = "<option value=''>请选择</option>";
                    //            for (var item in data) {
                    //                html += "<option value='" + data[item].SupplierId + "' " + "data-subtext='" + data[item].SupplierNo + "'>" + data[item].SupplierName + "</option>"
                    //            }
                    //            $(".selectpicker").empty();
                    //            $(".selectpicker").append(html)
                    //            $('.selectpicker').selectpicker('refresh');
                    //        }).catch(function (res) {
                    //        });
                    //} else {
                    //    yui.$axiosget('/StockIn/Search?text=' + text).then(function (res) {
                    //        var data = res.data.rows;
                    //        var html = "<option value=''>请选择</option>";
                    //        for (var item in data) {
                    //            html += "<option value='" + data[item].SupplierId + "' " + "data-subtext='" + data[item].SupplierNo + "'>" + data[item].SupplierName + "</option>"
                    //        }
                    //        $(".selectpicker").empty();
                    //        $(".selectpicker").append(html)
                    //        $('.selectpicker').selectpicker('refresh');
                    //    }).catch(function (res) {
                    //    });
                    //}
                });
                //$(divdom).on("keydown", function (event) {
                //    event.preventDefault();
                //    var dom = $("li[class='no-results']");
                //    if (dom.length > 0) {
                //        var text = divdom.value;
                //        yui.$axiosget('/StockIn/Search?text=' + text).then(function (res) {
                //            var data = res.data.rows;
                //            var html = "<option value=''>请选择</option>";
                //            for (var item in data) {
                //                html += "<option value='" + data[item].SupplierId + "' " + "data-subtext='" + data[item].SupplierNo + "'>" + data[item].SupplierName + "</option>"
                //            }
                //            $(".selectpicker").empty();
                //            $(".selectpicker").append(html)
                //            $('.selectpicker').selectpicker('refresh');
                //        }).catch(function (res) {
                //        });
                //    }
                //});
            });
        });
        var app = new Vue({
            el: "#app",
            data: {
                submit: "添加",
                StockInNo:"@Model.StockInNo",
                StockInId:"@Model.StockInId",
                Remark: "@Model.Remark",
                SupplierId: "@Model.SupplierId",
                OrderNo: "@Model.OrderNo",
                StockinType: "@Model.StockInType",
                SupplierList: [],
                url:''
            },
            computed: {
                count: function () {
                    return this.strLength(this.Remark, false);
                }
            },
            mounted: function(){
                var _self = this;
                _self.$nextTick(function () {
                    $(".selectpicker").selectpicker({
                        noneSelectedText: '请选择',
                    });
                    _self.searchSupplier("", 1);
                });
            },
            methods: {
                searchSupplier: function (val, type) {
                    _self = this;
                    console.info(val);
                    console.info(type);
                    if (type === 1) {
                        _self.url = "/Supplier/Search";
                    } else {
                        _self.url = "/Supplier/Search?text="+val;
                    }
                    yui.$axiosget(_self.url).then(function (res) {
                        _self.SupplierList = res.data.rows;
                        var html = "<option value=''>请选择</option>";
                        for (var item in _self.SupplierList) {
                            html += "<option value='" + _self.SupplierList[item].SupplierId + "' " + "data-subtext='" + _self.SupplierList[item].SupplierNo + "'>" + _self.SupplierList[item].SupplierName + "</option>"
                        }
                        if (type !== 1) {
                            $(".selectpicker").empty(html)
                        }
                        $(".selectpicker").append(html)
                        $('.selectpicker').selectpicker('refresh');
                        $('.selectpicker').selectpicker('val', _self.SupplierId);
                    }).catch(function (res) {
                    });
                },
                addL: function () {
                   var _self = this;
                    if (_self.SupplierId.length <= 0) {
                        layer.msg("请选择供应商", { icon: 2 });
                        return false;
                    }
                    if (_self.StockinType.length <= 0) {
                        layer.msg("请选择入库类型", { icon: 2 });
                        return false;
                    }
                    var index = layer.load(1, {
                        shade: [0.1, '#fff'] //0.1透明度的白色背景
                    });
                    var data = {
                        id: _self.StockInId,
                        SupplierId: _self.SupplierId,
                        StockinType: _self.StockinType,
                        OrderNo: _self.OrderNo,
                        Remark: _self.Remark
                    };
                    yui.$axiospostform('/StockIn/AddOrUpdate', data)
                        .then(function (response) {
                            if (response.data.Item1 === 101) {
                                layer.tips(response.data.Item2, '.layui-layer-setwin', {
                                    tips: [1, '#3595CC'],
                                    time: 3000
                                });
                                layer.close(index);
                                return false;
                            }
                            if (response.data.Item1) {
                                layer.msg(response.data.Item2, { icon: 1, time: 1000 });
                                setTimeout(function () {
                                    yui.layer_close3();
                                }, 500);
                            } else {
                                layer.msg(response.data.Item2 || errorMsg, { icon: 5 });
                            }
                            layer.close(index);
                        })
                        .catch(function (error) {
                            layer.close(index);
                        });
                }
            }
        });
    </script>
}

src/StoreYxWms/Views/StockIn/Preview.cshtml
@{
    Layout = "_LayoutH";
}
@section styles{
}
<div id="app" v-cloak>
    <form class="form-horizontal" onsubmit="return false">
        <div class="box-body" id="print">
            @*<table class="table">
                    <thead>
                        <tr>
                            <th style="white-space:nowrap">入库单号</th>
                            <th style="white-space:nowrap;margin-left:20px;">订单号</th>
                            <th style="white-space:nowrap;margin-left:20px;">供应商编号</th>
                            <th style="white-space:nowrap;margin-left:20px;">供应商名称</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="item in stockInList">
                            <td style="white-space:nowrap">{{item.StockInNo}}</td>
                            <td style="white-space:nowrap">{{item.OrderNo}}</td>
                            <td style="white-space:nowrap">{{item.SupplierNo}}</td>
                            <td style="white-space:nowrap">{{item.SupplierName}}</td>
                        </tr>
                    </tbody>
                </table>*@
            <br />
            <table class="table" style="border: 1px solid #ddd;width:100%">
                <caption style="text-align:center">明细</caption>
                <thead>
                    <tr>
                        <th style="white-space:nowrap">物料编号</th>
                        <th style="white-space:nowrap">物料名称</th>
                        <th style="white-space:nowrap">计划数量</th>
                        <th style="white-space:nowrap">实际数量</th>
                        <th style="white-space:nowrap">货架编号</th>
                        <th style="white-space:nowrap">货架名称</th>
                        <th style="white-space:nowrap">状态</th>
                        <th style="white-space:nowrap">审核人</th>
                        <th style="white-space:nowrap">审核时间</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="item in stockInDList">
                        <td style="white-space:nowrap">{{item.MaterialNo}}</td>
                        <td style="white-space:nowrap">{{item.MaterialName}}</td>
                        <td style="white-space:nowrap">{{item.PlanInQty}}</td>
                        <td style="white-space:nowrap">{{item.ActInQty}}</td>
                        <td style="white-space:nowrap">{{item.StorageRackNo}}</td>
                        <td style="white-space:nowrap">{{item.StorageRackName}}</td>
                        <td style="white-space:nowrap">{{item.Status}}</td>
                        <td style="white-space:nowrap">{{item.AName}}</td>
                        <td style="white-space:nowrap">{{formatL(item.AuditinTime)}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="box-footer">
            <div class="pull-right box-tools">
                <input v-on:click="printL" class="btn btn-primary radius" type="submit" v-model="submit">
            </div>
        </div>
    </form>
</div>

@section scripts{
    <script src="~/lib/lodop/LodopFuncs.js"></script>
    <script>
        var app = new Vue({
            el: "#app",
            data: {
                submit: "打印",
                stockInId: "@ViewBag.StockInId",
                stockInList: [],
                stockInDList: [],
                stockInNo:''

            },
            computed: {
            },
            mounted: function () {
                var _self = this;
                _self.$nextTick(function () {
                    _self.loadL();
                });
            },
            methods: {
                loadL: function () {
                    var _self = this;
                    yui.$axiosget('/StockIn/PreviewJson?id=' + _self.stockInId)
                        .then(function (response) {
                            _self.stockInList = response.data.Item2;
                            if (_self.stockInList.length>0) {
                                _self.stockInNo = _self.stockInList[0].StockInNo;
                            }
                            _self.stockInDList = response.data.Item4;
                        })
                        .catch(function (error) {
                            layer.msg(error.message, { icon: 5 });
                        });
                },
                printL: function () {
                    var _self = this;
                    var html = document.getElementById("print").innerHTML;
                    //console.info(html);
                    var LODOP = getLodop();
                    LODOP.PRINT_INIT("入库单")
                    LODOP.ADD_PRINT_TEXT(45, 325, 146, 45, "入库单");
                    LODOP.SET_PRINT_STYLEA(0, "FontSize", 17);
                    LODOP.ADD_PRINT_BARCODE(40, 555, 257, 141, "QRCode", _self.stockInNo);
                    LODOP.ADD_PRINT_HTM(203, 53, 620, 600, html);
                    if (_self.stockInList.length > 0) {
                       LODOP.ADD_PRINT_TEXT(92, 33, 205, 25, "入库单号:" + _self.stockInList[0].StockInNo);
                       LODOP.ADD_PRINT_TEXT(191, 33,205, 25, "供应商名称:" + _self.stockInList[0].OrderNo);
                       LODOP.ADD_PRINT_TEXT(158, 33,205, 25, "供应商编号:" + _self.stockInList[0].SupplierNo);
                       LODOP.ADD_PRINT_TEXT(127, 33,205, 25, "订单号:" + _self.stockInList[0].SupplierName);
                    }
                    //LODOP.ADD_PRINT_TABLE("0", "0", "210", "290", html);
                    LODOP.PRINT_DESIGN();
                },
                formatL: function (val) {
                    return this.jsonDateFormat(val);
                }

            }
        });
    </script>
}